---
title: 'Week 2 (Class #3)'
author: "Hannah Irish"
date: "2023-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
library(nloptr)
```

| Turn in the html document for turning in homework

Using "R examples for ESM 242" from 10-9 module:

Find the T that maximizes function

Need the functional form and the parameters:

p = 1

a = 10

b = 53.27

delta = 0.05

c = 300


Create PVNB function
```{r}
PVNB <- function(t, a, b, p, delta, c){
  Q = exp(a-b/t)
  bennies = p*Q*exp(-delta*t) - c
  return(-bennies)
}
```

Setting up to use nloptr
```{r}
##his Rmarkdown says "always include this options statement" -- will be given in homework assignment
options=list("algorithm"="NLOPT_LN_COBYLA",xtol_rel=1e-8,maxeval=16000)

```

Using nloptr
```{r}
ex_1a=nloptr(x0=1,##beginning stock
          eval_f=PVNB, ##function you're maximizing
          lb=0, ##lower bound
          opts = options, ##options set above
          a=10, b= 53.27, p=1, delta=0.05, c=300) ## the other parameters besides the one you're deriving across

print(ex_1a$solution)
```





















