---
title: "Class 4 (Week 2)"
author: "Hannah Irish"
date: "2023-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nloptr)
library(knitr)
```


**Example 2**

pYt is the profit and (c/2)*Y^2/Xt is the cost -- the cost depends on the stock, standard for fisheries. There is lower cost when there are more fish. When there are fewer fish, it's more expensive to catch them and it's easier to catch fish when the stock is really big

optimal value of catchability coefficient:

```{r}

objective_func2 <- function(alpha, init_state, dsct, p, c, r, K, period){
  state <- vector(mode = "numeric", length = 0)
  yield <- vector(mode = "numeric", length = 0)
  benefits <- vector(mode = "numeric", length = 0)
  
  
  ##set up initial period
  
  state[1] = init_state
  yield[1] = alpha*state[1]
  benefits[1] = p*yield - (c/2)*(yield[1]^2/state[1])
  
  
  for (i in 2:(period+1)){
    state[i] = state[i-1] + r*state[i-1]*(1-state[i-1]/K)-yield[i-1]
    yield[i] = alpha*state[i]
    benefits[i] = p*yield[i] - (c/2)*(yield[i]^2/state[i])
  }
  
  
  t = seq(from=0, period)
  
  pv = dsct^t*benefits
  
  npv = sum(pv)
  
  return(-npv)
}

local_opts <- list("algorithm" = "NLOPT_LN_COBYLA", xtol_rel = 1e-15)
options = list("algorithm" = "NLOPT_LN_AUGLAG", xtol_rel=1e-15, maxeval=16000, "local_opts"=local_opts)

ans_2a=nloptr(x0=0.5, eval_f = objective_func2, lb=0, opts = options, init_state=0.1, dsct=1/1.05, p=5, c=1, r=1, K=1, period=19)

print(ans_2a$solution)


ans_2b=nloptr(x0=rep(0.5,time=20),eval_f=objective_func2,
              lb=rep(0,times=20),
              ub=rep(1,times=20),
              opts = options,init_state=0.1,dsct=1/1.05,p=5,c=1,r=1,K=1,period=19)



print(-ans_2b$solution)
```

